name: al_iman_attendance
description: تطبيق حضور وانصراف الموظفين - مصنع الإيمان للمراتب والمفروشات
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  geolocator: ^13.0.1        # لجلب موقع GPS وحساب المسافة
  local_auth: ^2.3.0         # لبصمة الإصبع/الوجه المحلية على الجهاز
  http: ^1.2.2               # للاتصال بالـ API
  shared_preferences: ^2.3.2 # لحفظ بيانات تسجيل دخول الموظف على الجهاز

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
